version: '2'
services:
  renren-admin:
    image: renren/renren-admin
    ports:
    - "8083:8083"
    environment:
    - spring.profiles.active=dev
  renren-api:
    image: renren/renren-api
    ports:
    - "8081:8081"
    environment:
    - spring.profiles.active=dev
