server:
  port: 9113

spring:
  application:
    name: renren-bank
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.72.211:8848
        namespace: be188a42-2c90-487c-aece-802135d27942
  datasource:
    url: jdbc:mysql://120.48.66.56:3306/bank?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2916435196Liu@
 # rabbitmq:
  #  host: 192.168.57.129
   # port: 5672
   # username: guest
    #password: guest

mybatis:
  mapper-locations: classpath:com/bw/bank/mapper/*Mapper.xml

key:
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALUpCyzlD9vxK+awa4mc1Z0NzupRm3YFixf39tWPW4+De1eJ7C5NBby1AhtUaz9VUQjW15CKDmC/1S9wSJBa828CAwEAAQ==
  privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAtSkLLOUP2/Er5rBriZzVnQ3O6lGbdgWLF/f21Y9bj4N7V4nsLk0FvLUCG1RrP1VRCNbXkIoOYL/VL3BIkFrzbwIDAQABAkBcqQanSu5msB+lWh1XANod/78TCPS8VC+F7fXZ2/6YE2mv6gB4pk5Kc/hovXB0xoUu8DkyhQ+edGygWHALcoJpAiEA8IYmy9jO+R9jymaWkhffKH7oZkrcDSErWFrK2XwafnMCIQDA0RGfCsn2J+tTZHKB+eJURbzNCGIVmNdLpm01Eb4cFQIhAMHUekNgTzs37qVXkxPcpPvveb2lqjvydQnY8QvfFUK9AiBl+GssRAVo49WlJZMVP/S9AqCFgjB1IX6CqIJKtZZnvQIgW5xkH7w18chMrjxr9xbcr9+oTJRqgRBAZeerr/altxc=
