server:
  port: 9111

spring:
  application:
    name: loans-service-plan
  datasource:
    druid:
      url: jdbc:mysql://120.48.66.56:3306/bank?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 2916435196Liu@

mybatis:
  mapper-locations: classpath:com/loans/plan/mapper/*Mapper.xml

ngrok:
  url: bwbd.vipgz1.91tunnel.com


